"""inital

Revision ID: b3b36f81a9eb
Revises: 
Create Date: 2026-02-21 13:26:27.351628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3b36f81a9eb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listener_checkpoints',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('network', sa.String(length=50), nullable=False),
    sa.Column('last_block', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('network')
    )
    op.create_table('services',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('price_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_services_slug'), 'services', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('subscription_intents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('wallet_address', sa.String(length=42), nullable=False),
    sa.Column('expected_amount', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('tx_hash', sa.String(length=66), nullable=True),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'expired', 'fulfilled', 'unallocated', name='intent_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tx_hash')
    )
    op.create_index(op.f('ix_subscription_intents_status'), 'subscription_intents', ['status'], unique=False)
    op.create_index(op.f('ix_subscription_intents_user_id'), 'subscription_intents', ['user_id'], unique=False)
    op.create_table('virtual_cards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('subscription_intent_id', sa.UUID(), nullable=False),
    sa.Column('reloadly_card_id', sa.String(length=100), nullable=False),
    sa.Column('last4', sa.String(length=4), nullable=False),
    sa.Column('expiry_month', sa.String(length=2), nullable=False),
    sa.Column('expiry_year', sa.String(length=4), nullable=False),
    sa.Column('encrypted_card_number', sa.Text(), nullable=True),
    sa.Column('encrypted_cvv', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('active', 'awaiting_charge', 'used', 'revoked', name='card_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subscription_intent_id'], ['subscription_intents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subscription_intent_id')
    )
    op.create_index(op.f('ix_virtual_cards_status'), 'virtual_cards', ['status'], unique=False)
    op.create_index(op.f('ix_virtual_cards_user_id'), 'virtual_cards', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_virtual_cards_user_id'), table_name='virtual_cards')
    op.drop_index(op.f('ix_virtual_cards_status'), table_name='virtual_cards')
    op.drop_table('virtual_cards')
    op.drop_index(op.f('ix_subscription_intents_user_id'), table_name='subscription_intents')
    op.drop_index(op.f('ix_subscription_intents_status'), table_name='subscription_intents')
    op.drop_table('subscription_intents')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_services_slug'), table_name='services')
    op.drop_table('services')
    op.drop_table('listener_checkpoints')
    # ### end Alembic commands ###
